<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>BluetoothBattery_App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseWPF>true</UseWPF>
    <StartupObject>BluetoothBattery_App.Program</StartupObject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\AppIcon.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BluetoothBattery.Core\BluetoothBattery.Core.csproj" />
  </ItemGroup>
</Project>
